#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Escuela")]
	public partial class EscuelaDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAlumno(tblAlumno instance);
    partial void UpdatetblAlumno(tblAlumno instance);
    partial void DeletetblAlumno(tblAlumno instance);
    partial void InserttblUsuario(tblUsuario instance);
    partial void UpdatetblUsuario(tblUsuario instance);
    partial void DeletetblUsuario(tblUsuario instance);
    partial void InserttblCargasAlumno(tblCargasAlumno instance);
    partial void UpdatetblCargasAlumno(tblCargasAlumno instance);
    partial void DeletetblCargasAlumno(tblCargasAlumno instance);
    partial void InserttblCargasDocente(tblCargasDocente instance);
    partial void UpdatetblCargasDocente(tblCargasDocente instance);
    partial void DeletetblCargasDocente(tblCargasDocente instance);
    partial void InserttblCarrera(tblCarrera instance);
    partial void UpdatetblCarrera(tblCarrera instance);
    partial void DeletetblCarrera(tblCarrera instance);
    partial void InserttblMaestro(tblMaestro instance);
    partial void UpdatetblMaestro(tblMaestro instance);
    partial void DeletetblMaestro(tblMaestro instance);
    partial void InserttblMateria(tblMateria instance);
    partial void UpdatetblMateria(tblMateria instance);
    partial void DeletetblMateria(tblMateria instance);
    partial void InserttblMateriasCarrera(tblMateriasCarrera instance);
    partial void UpdatetblMateriasCarrera(tblMateriasCarrera instance);
    partial void DeletetblMateriasCarrera(tblMateriasCarrera instance);
    #endregion
		
		public EscuelaDatabaseDataContext() : 
				base(global::Escuela.Properties.Settings.Default.EscuelaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EscuelaDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscuelaDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscuelaDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscuelaDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAlumno> tblAlumnos
		{
			get
			{
				return this.GetTable<tblAlumno>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuario> tblUsuarios
		{
			get
			{
				return this.GetTable<tblUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tblCargasAlumno> tblCargasAlumnos
		{
			get
			{
				return this.GetTable<tblCargasAlumno>();
			}
		}
		
		public System.Data.Linq.Table<tblCargasDocente> tblCargasDocentes
		{
			get
			{
				return this.GetTable<tblCargasDocente>();
			}
		}
		
		public System.Data.Linq.Table<tblCarrera> tblCarreras
		{
			get
			{
				return this.GetTable<tblCarrera>();
			}
		}
		
		public System.Data.Linq.Table<tblMaestro> tblMaestros
		{
			get
			{
				return this.GetTable<tblMaestro>();
			}
		}
		
		public System.Data.Linq.Table<tblMateria> tblMaterias
		{
			get
			{
				return this.GetTable<tblMateria>();
			}
		}
		
		public System.Data.Linq.Table<tblMateriasCarrera> tblMateriasCarreras
		{
			get
			{
				return this.GetTable<tblMateriasCarrera>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarAlumno")]
		public int ActualizarAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlumnoID", DbType="Int")] System.Nullable<int> alumnoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreAlumno", DbType="VarChar(1)")] string nombreAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), alumnoID, nombreAlumno, carreraID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerUsuarios")]
		public ISingleResult<ObtenerUsuariosResult> ObtenerUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarCargaAlumno")]
		public int ActualizarCargaAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CargaID", DbType="Int")] System.Nullable<int> cargaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlumnoID", DbType="Int")] System.Nullable<int> alumnoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MateriaID", DbType="Int")] System.Nullable<int> materiaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaestroID", DbType="Int")] System.Nullable<int> maestroID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargaID, alumnoID, carreraID, materiaID, maestroID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarCargaDocente")]
		public int ActualizarCargaDocente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CargaID", DbType="Int")] System.Nullable<int> cargaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaestroID", DbType="Int")] System.Nullable<int> maestroID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MateriaID", DbType="Int")] System.Nullable<int> materiaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargaID, maestroID, carreraID, materiaID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarCarrera")]
		public int ActualizarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreCarrera", DbType="VarChar(1)")] string nombreCarrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carreraID, nombreCarrera);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarMaestro")]
		public int ActualizarMaestro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaestroID", DbType="Int")] System.Nullable<int> maestroID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreMaestro", DbType="VarChar(1)")] string nombreMaestro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dirección", DbType="VarChar(1)")] string dirección)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maestroID, nombreMaestro, dirección);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarUsuario")]
		public int ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(1)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(1)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID, nombreUsuario, contraseña);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarAlumno")]
		public ISingleResult<BuscarAlumnoResult> BuscarAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlumnoID", DbType="Int")] System.Nullable<int> alumnoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), alumnoID);
			return ((ISingleResult<BuscarAlumnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarAlumnoIDPorNombreAlumno")]
		public ISingleResult<BuscarAlumnoIDPorNombreAlumnoResult> BuscarAlumnoIDPorNombreAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreAlumno", DbType="VarChar(1)")] string nombreAlumno)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreAlumno);
			return ((ISingleResult<BuscarAlumnoIDPorNombreAlumnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCargaAlumno")]
		public ISingleResult<BuscarCargaAlumnoResult> BuscarCargaAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CargaID", DbType="Int")] System.Nullable<int> cargaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargaID);
			return ((ISingleResult<BuscarCargaAlumnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCargaDocente")]
		public ISingleResult<BuscarCargaDocenteResult> BuscarCargaDocente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CargaID", DbType="Int")] System.Nullable<int> cargaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargaID);
			return ((ISingleResult<BuscarCargaDocenteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCarrera")]
		public ISingleResult<BuscarCarreraResult> BuscarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carreraID);
			return ((ISingleResult<BuscarCarreraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarMaestro")]
		public ISingleResult<BuscarMaestroResult> BuscarMaestro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaestroID", DbType="Int")] System.Nullable<int> maestroID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maestroID);
			return ((ISingleResult<BuscarMaestroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarMaestrosPorMateriaID")]
		public ISingleResult<BuscarMaestrosPorMateriaIDResult> BuscarMaestrosPorMateriaID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MateriaID", DbType="Int")] System.Nullable<int> materiaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), materiaID);
			return ((ISingleResult<BuscarMaestrosPorMateriaIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarMateriasPorCarreraID")]
		public ISingleResult<BuscarMateriasPorCarreraIDResult> BuscarMateriasPorCarreraID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carreraID);
			return ((ISingleResult<BuscarMateriasPorCarreraIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarUsuario")]
		public ISingleResult<BuscarUsuarioResult> BuscarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((ISingleResult<BuscarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarAlumno")]
		public int EliminarAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlumnoID", DbType="Int")] System.Nullable<int> alumnoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), alumnoID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCargaAlumno")]
		public int EliminarCargaAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CargaID", DbType="Int")] System.Nullable<int> cargaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargaID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCargaDocente")]
		public int EliminarCargaDocente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CargaID", DbType="Int")] System.Nullable<int> cargaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargaID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCarrera")]
		public int EliminarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), carreraID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarMaestro")]
		public int EliminarMaestro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaestroID", DbType="Int")] System.Nullable<int> maestroID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maestroID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarUsuario")]
		public int EliminarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarAlumno")]
		public int InsertarAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreAlumno", DbType="VarChar(1)")] string nombreAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreAlumno, carreraID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCargaAlumno")]
		public int InsertarCargaAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlumnoID", DbType="Int")] System.Nullable<int> alumnoID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MateriaID", DbType="Int")] System.Nullable<int> materiaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaestroID", DbType="Int")] System.Nullable<int> maestroID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), alumnoID, carreraID, materiaID, maestroID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCargaDocente")]
		public int InsertarCargaDocente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaestroID", DbType="Int")] System.Nullable<int> maestroID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarreraID", DbType="Int")] System.Nullable<int> carreraID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MateriaID", DbType="Int")] System.Nullable<int> materiaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maestroID, carreraID, materiaID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCarrera")]
		public int InsertarCarrera([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreCarrera", DbType="VarChar(1)")] string nombreCarrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreCarrera);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarMaestro")]
		public int InsertarMaestro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreMaestro", DbType="VarChar(1)")] string nombreMaestro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dirección", DbType="VarChar(1)")] string dirección)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreMaestro, dirección);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarUsuario")]
		public int InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(1)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(1)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreUsuario, contraseña);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerAlumnos")]
		public ISingleResult<ObtenerAlumnosResult> ObtenerAlumnos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerAlumnosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerCargasAlumnos")]
		public ISingleResult<ObtenerCargasAlumnosResult> ObtenerCargasAlumnos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerCargasAlumnosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerCargasDocentes")]
		public ISingleResult<ObtenerCargasDocentesResult> ObtenerCargasDocentes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerCargasDocentesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerCarreras")]
		public ISingleResult<ObtenerCarrerasResult> ObtenerCarreras()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerCarrerasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerMaestros")]
		public ISingleResult<ObtenerMaestrosResult> ObtenerMaestros()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ObtenerMaestrosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAlumnos")]
	public partial class tblAlumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AlumnoID;
		
		private string _NombreAlumno;
		
		private int _CarreraID;
		
		private EntitySet<tblCargasAlumno> _tblCargasAlumnos;
		
		private EntityRef<tblCarrera> _tblCarrera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAlumnoIDChanging(int value);
    partial void OnAlumnoIDChanged();
    partial void OnNombreAlumnoChanging(string value);
    partial void OnNombreAlumnoChanged();
    partial void OnCarreraIDChanging(int value);
    partial void OnCarreraIDChanged();
    #endregion
		
		public tblAlumno()
		{
			this._tblCargasAlumnos = new EntitySet<tblCargasAlumno>(new Action<tblCargasAlumno>(this.attach_tblCargasAlumnos), new Action<tblCargasAlumno>(this.detach_tblCargasAlumnos));
			this._tblCarrera = default(EntityRef<tblCarrera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AlumnoID
		{
			get
			{
				return this._AlumnoID;
			}
			set
			{
				if ((this._AlumnoID != value))
				{
					this.OnAlumnoIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoID = value;
					this.SendPropertyChanged("AlumnoID");
					this.OnAlumnoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreAlumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreAlumno
		{
			get
			{
				return this._NombreAlumno;
			}
			set
			{
				if ((this._NombreAlumno != value))
				{
					this.OnNombreAlumnoChanging(value);
					this.SendPropertyChanging();
					this._NombreAlumno = value;
					this.SendPropertyChanged("NombreAlumno");
					this.OnNombreAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarreraID", DbType="Int NOT NULL")]
		public int CarreraID
		{
			get
			{
				return this._CarreraID;
			}
			set
			{
				if ((this._CarreraID != value))
				{
					if (this._tblCarrera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarreraIDChanging(value);
					this.SendPropertyChanging();
					this._CarreraID = value;
					this.SendPropertyChanged("CarreraID");
					this.OnCarreraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAlumno_tblCargasAlumno", Storage="_tblCargasAlumnos", ThisKey="AlumnoID", OtherKey="AlumnoID")]
		public EntitySet<tblCargasAlumno> tblCargasAlumnos
		{
			get
			{
				return this._tblCargasAlumnos;
			}
			set
			{
				this._tblCargasAlumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblAlumno", Storage="_tblCarrera", ThisKey="CarreraID", OtherKey="CarreraID", IsForeignKey=true)]
		public tblCarrera tblCarrera
		{
			get
			{
				return this._tblCarrera.Entity;
			}
			set
			{
				tblCarrera previousValue = this._tblCarrera.Entity;
				if (((previousValue != value) 
							|| (this._tblCarrera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCarrera.Entity = null;
						previousValue.tblAlumnos.Remove(this);
					}
					this._tblCarrera.Entity = value;
					if ((value != null))
					{
						value.tblAlumnos.Add(this);
						this._CarreraID = value.CarreraID;
					}
					else
					{
						this._CarreraID = default(int);
					}
					this.SendPropertyChanged("tblCarrera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblAlumno = this;
		}
		
		private void detach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblAlumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuarios")]
	public partial class tblUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioID;
		
		private string _NombreUsuario;
		
		private string _Contraseña;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    #endregion
		
		public tblUsuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCargasAlumnos")]
	public partial class tblCargasAlumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CargaID;
		
		private int _AlumnoID;
		
		private int _CarreraID;
		
		private int _MateriaID;
		
		private int _MaestroID;
		
		private EntityRef<tblAlumno> _tblAlumno;
		
		private EntityRef<tblCarrera> _tblCarrera;
		
		private EntityRef<tblMaestro> _tblMaestro;
		
		private EntityRef<tblMateria> _tblMateria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCargaIDChanging(int value);
    partial void OnCargaIDChanged();
    partial void OnAlumnoIDChanging(int value);
    partial void OnAlumnoIDChanged();
    partial void OnCarreraIDChanging(int value);
    partial void OnCarreraIDChanged();
    partial void OnMateriaIDChanging(int value);
    partial void OnMateriaIDChanged();
    partial void OnMaestroIDChanging(int value);
    partial void OnMaestroIDChanged();
    #endregion
		
		public tblCargasAlumno()
		{
			this._tblAlumno = default(EntityRef<tblAlumno>);
			this._tblCarrera = default(EntityRef<tblCarrera>);
			this._tblMaestro = default(EntityRef<tblMaestro>);
			this._tblMateria = default(EntityRef<tblMateria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CargaID
		{
			get
			{
				return this._CargaID;
			}
			set
			{
				if ((this._CargaID != value))
				{
					this.OnCargaIDChanging(value);
					this.SendPropertyChanging();
					this._CargaID = value;
					this.SendPropertyChanged("CargaID");
					this.OnCargaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", DbType="Int NOT NULL")]
		public int AlumnoID
		{
			get
			{
				return this._AlumnoID;
			}
			set
			{
				if ((this._AlumnoID != value))
				{
					if (this._tblAlumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAlumnoIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoID = value;
					this.SendPropertyChanged("AlumnoID");
					this.OnAlumnoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarreraID", DbType="Int NOT NULL")]
		public int CarreraID
		{
			get
			{
				return this._CarreraID;
			}
			set
			{
				if ((this._CarreraID != value))
				{
					if (this._tblCarrera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarreraIDChanging(value);
					this.SendPropertyChanging();
					this._CarreraID = value;
					this.SendPropertyChanged("CarreraID");
					this.OnCarreraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MateriaID", DbType="Int NOT NULL")]
		public int MateriaID
		{
			get
			{
				return this._MateriaID;
			}
			set
			{
				if ((this._MateriaID != value))
				{
					if (this._tblMateria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMateriaIDChanging(value);
					this.SendPropertyChanging();
					this._MateriaID = value;
					this.SendPropertyChanged("MateriaID");
					this.OnMateriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaestroID", DbType="Int NOT NULL")]
		public int MaestroID
		{
			get
			{
				return this._MaestroID;
			}
			set
			{
				if ((this._MaestroID != value))
				{
					if (this._tblMaestro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaestroIDChanging(value);
					this.SendPropertyChanging();
					this._MaestroID = value;
					this.SendPropertyChanged("MaestroID");
					this.OnMaestroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAlumno_tblCargasAlumno", Storage="_tblAlumno", ThisKey="AlumnoID", OtherKey="AlumnoID", IsForeignKey=true)]
		public tblAlumno tblAlumno
		{
			get
			{
				return this._tblAlumno.Entity;
			}
			set
			{
				tblAlumno previousValue = this._tblAlumno.Entity;
				if (((previousValue != value) 
							|| (this._tblAlumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAlumno.Entity = null;
						previousValue.tblCargasAlumnos.Remove(this);
					}
					this._tblAlumno.Entity = value;
					if ((value != null))
					{
						value.tblCargasAlumnos.Add(this);
						this._AlumnoID = value.AlumnoID;
					}
					else
					{
						this._AlumnoID = default(int);
					}
					this.SendPropertyChanged("tblAlumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblCargasAlumno", Storage="_tblCarrera", ThisKey="CarreraID", OtherKey="CarreraID", IsForeignKey=true)]
		public tblCarrera tblCarrera
		{
			get
			{
				return this._tblCarrera.Entity;
			}
			set
			{
				tblCarrera previousValue = this._tblCarrera.Entity;
				if (((previousValue != value) 
							|| (this._tblCarrera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCarrera.Entity = null;
						previousValue.tblCargasAlumnos.Remove(this);
					}
					this._tblCarrera.Entity = value;
					if ((value != null))
					{
						value.tblCargasAlumnos.Add(this);
						this._CarreraID = value.CarreraID;
					}
					else
					{
						this._CarreraID = default(int);
					}
					this.SendPropertyChanged("tblCarrera");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMaestro_tblCargasAlumno", Storage="_tblMaestro", ThisKey="MaestroID", OtherKey="MaestroID", IsForeignKey=true)]
		public tblMaestro tblMaestro
		{
			get
			{
				return this._tblMaestro.Entity;
			}
			set
			{
				tblMaestro previousValue = this._tblMaestro.Entity;
				if (((previousValue != value) 
							|| (this._tblMaestro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMaestro.Entity = null;
						previousValue.tblCargasAlumnos.Remove(this);
					}
					this._tblMaestro.Entity = value;
					if ((value != null))
					{
						value.tblCargasAlumnos.Add(this);
						this._MaestroID = value.MaestroID;
					}
					else
					{
						this._MaestroID = default(int);
					}
					this.SendPropertyChanged("tblMaestro");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMateria_tblCargasAlumno", Storage="_tblMateria", ThisKey="MateriaID", OtherKey="MateriaID", IsForeignKey=true)]
		public tblMateria tblMateria
		{
			get
			{
				return this._tblMateria.Entity;
			}
			set
			{
				tblMateria previousValue = this._tblMateria.Entity;
				if (((previousValue != value) 
							|| (this._tblMateria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMateria.Entity = null;
						previousValue.tblCargasAlumnos.Remove(this);
					}
					this._tblMateria.Entity = value;
					if ((value != null))
					{
						value.tblCargasAlumnos.Add(this);
						this._MateriaID = value.MateriaID;
					}
					else
					{
						this._MateriaID = default(int);
					}
					this.SendPropertyChanged("tblMateria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCargasDocentes")]
	public partial class tblCargasDocente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CargaID;
		
		private int _MaestroID;
		
		private int _CarreraID;
		
		private int _MateriaID;
		
		private EntityRef<tblCarrera> _tblCarrera;
		
		private EntityRef<tblMaestro> _tblMaestro;
		
		private EntityRef<tblMateria> _tblMateria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCargaIDChanging(int value);
    partial void OnCargaIDChanged();
    partial void OnMaestroIDChanging(int value);
    partial void OnMaestroIDChanged();
    partial void OnCarreraIDChanging(int value);
    partial void OnCarreraIDChanged();
    partial void OnMateriaIDChanging(int value);
    partial void OnMateriaIDChanged();
    #endregion
		
		public tblCargasDocente()
		{
			this._tblCarrera = default(EntityRef<tblCarrera>);
			this._tblMaestro = default(EntityRef<tblMaestro>);
			this._tblMateria = default(EntityRef<tblMateria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CargaID
		{
			get
			{
				return this._CargaID;
			}
			set
			{
				if ((this._CargaID != value))
				{
					this.OnCargaIDChanging(value);
					this.SendPropertyChanging();
					this._CargaID = value;
					this.SendPropertyChanged("CargaID");
					this.OnCargaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaestroID", DbType="Int NOT NULL")]
		public int MaestroID
		{
			get
			{
				return this._MaestroID;
			}
			set
			{
				if ((this._MaestroID != value))
				{
					if (this._tblMaestro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaestroIDChanging(value);
					this.SendPropertyChanging();
					this._MaestroID = value;
					this.SendPropertyChanged("MaestroID");
					this.OnMaestroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarreraID", DbType="Int NOT NULL")]
		public int CarreraID
		{
			get
			{
				return this._CarreraID;
			}
			set
			{
				if ((this._CarreraID != value))
				{
					if (this._tblCarrera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarreraIDChanging(value);
					this.SendPropertyChanging();
					this._CarreraID = value;
					this.SendPropertyChanged("CarreraID");
					this.OnCarreraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MateriaID", DbType="Int NOT NULL")]
		public int MateriaID
		{
			get
			{
				return this._MateriaID;
			}
			set
			{
				if ((this._MateriaID != value))
				{
					if (this._tblMateria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMateriaIDChanging(value);
					this.SendPropertyChanging();
					this._MateriaID = value;
					this.SendPropertyChanged("MateriaID");
					this.OnMateriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblCargasDocente", Storage="_tblCarrera", ThisKey="CarreraID", OtherKey="CarreraID", IsForeignKey=true)]
		public tblCarrera tblCarrera
		{
			get
			{
				return this._tblCarrera.Entity;
			}
			set
			{
				tblCarrera previousValue = this._tblCarrera.Entity;
				if (((previousValue != value) 
							|| (this._tblCarrera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCarrera.Entity = null;
						previousValue.tblCargasDocentes.Remove(this);
					}
					this._tblCarrera.Entity = value;
					if ((value != null))
					{
						value.tblCargasDocentes.Add(this);
						this._CarreraID = value.CarreraID;
					}
					else
					{
						this._CarreraID = default(int);
					}
					this.SendPropertyChanged("tblCarrera");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMaestro_tblCargasDocente", Storage="_tblMaestro", ThisKey="MaestroID", OtherKey="MaestroID", IsForeignKey=true)]
		public tblMaestro tblMaestro
		{
			get
			{
				return this._tblMaestro.Entity;
			}
			set
			{
				tblMaestro previousValue = this._tblMaestro.Entity;
				if (((previousValue != value) 
							|| (this._tblMaestro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMaestro.Entity = null;
						previousValue.tblCargasDocentes.Remove(this);
					}
					this._tblMaestro.Entity = value;
					if ((value != null))
					{
						value.tblCargasDocentes.Add(this);
						this._MaestroID = value.MaestroID;
					}
					else
					{
						this._MaestroID = default(int);
					}
					this.SendPropertyChanged("tblMaestro");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMateria_tblCargasDocente", Storage="_tblMateria", ThisKey="MateriaID", OtherKey="MateriaID", IsForeignKey=true)]
		public tblMateria tblMateria
		{
			get
			{
				return this._tblMateria.Entity;
			}
			set
			{
				tblMateria previousValue = this._tblMateria.Entity;
				if (((previousValue != value) 
							|| (this._tblMateria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMateria.Entity = null;
						previousValue.tblCargasDocentes.Remove(this);
					}
					this._tblMateria.Entity = value;
					if ((value != null))
					{
						value.tblCargasDocentes.Add(this);
						this._MateriaID = value.MateriaID;
					}
					else
					{
						this._MateriaID = default(int);
					}
					this.SendPropertyChanged("tblMateria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarreras")]
	public partial class tblCarrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CarreraID;
		
		private string _NombreCarrera;
		
		private EntitySet<tblAlumno> _tblAlumnos;
		
		private EntitySet<tblCargasAlumno> _tblCargasAlumnos;
		
		private EntitySet<tblCargasDocente> _tblCargasDocentes;
		
		private EntitySet<tblMateriasCarrera> _tblMateriasCarreras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarreraIDChanging(int value);
    partial void OnCarreraIDChanged();
    partial void OnNombreCarreraChanging(string value);
    partial void OnNombreCarreraChanged();
    #endregion
		
		public tblCarrera()
		{
			this._tblAlumnos = new EntitySet<tblAlumno>(new Action<tblAlumno>(this.attach_tblAlumnos), new Action<tblAlumno>(this.detach_tblAlumnos));
			this._tblCargasAlumnos = new EntitySet<tblCargasAlumno>(new Action<tblCargasAlumno>(this.attach_tblCargasAlumnos), new Action<tblCargasAlumno>(this.detach_tblCargasAlumnos));
			this._tblCargasDocentes = new EntitySet<tblCargasDocente>(new Action<tblCargasDocente>(this.attach_tblCargasDocentes), new Action<tblCargasDocente>(this.detach_tblCargasDocentes));
			this._tblMateriasCarreras = new EntitySet<tblMateriasCarrera>(new Action<tblMateriasCarrera>(this.attach_tblMateriasCarreras), new Action<tblMateriasCarrera>(this.detach_tblMateriasCarreras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarreraID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CarreraID
		{
			get
			{
				return this._CarreraID;
			}
			set
			{
				if ((this._CarreraID != value))
				{
					this.OnCarreraIDChanging(value);
					this.SendPropertyChanging();
					this._CarreraID = value;
					this.SendPropertyChanged("CarreraID");
					this.OnCarreraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCarrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string NombreCarrera
		{
			get
			{
				return this._NombreCarrera;
			}
			set
			{
				if ((this._NombreCarrera != value))
				{
					this.OnNombreCarreraChanging(value);
					this.SendPropertyChanging();
					this._NombreCarrera = value;
					this.SendPropertyChanged("NombreCarrera");
					this.OnNombreCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblAlumno", Storage="_tblAlumnos", ThisKey="CarreraID", OtherKey="CarreraID")]
		public EntitySet<tblAlumno> tblAlumnos
		{
			get
			{
				return this._tblAlumnos;
			}
			set
			{
				this._tblAlumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblCargasAlumno", Storage="_tblCargasAlumnos", ThisKey="CarreraID", OtherKey="CarreraID")]
		public EntitySet<tblCargasAlumno> tblCargasAlumnos
		{
			get
			{
				return this._tblCargasAlumnos;
			}
			set
			{
				this._tblCargasAlumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblCargasDocente", Storage="_tblCargasDocentes", ThisKey="CarreraID", OtherKey="CarreraID")]
		public EntitySet<tblCargasDocente> tblCargasDocentes
		{
			get
			{
				return this._tblCargasDocentes;
			}
			set
			{
				this._tblCargasDocentes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblMateriasCarrera", Storage="_tblMateriasCarreras", ThisKey="CarreraID", OtherKey="CarreraID")]
		public EntitySet<tblMateriasCarrera> tblMateriasCarreras
		{
			get
			{
				return this._tblMateriasCarreras;
			}
			set
			{
				this._tblMateriasCarreras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblAlumnos(tblAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = this;
		}
		
		private void detach_tblAlumnos(tblAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = null;
		}
		
		private void attach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = this;
		}
		
		private void detach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = null;
		}
		
		private void attach_tblCargasDocentes(tblCargasDocente entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = this;
		}
		
		private void detach_tblCargasDocentes(tblCargasDocente entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = null;
		}
		
		private void attach_tblMateriasCarreras(tblMateriasCarrera entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = this;
		}
		
		private void detach_tblMateriasCarreras(tblMateriasCarrera entity)
		{
			this.SendPropertyChanging();
			entity.tblCarrera = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMaestros")]
	public partial class tblMaestro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaestroID;
		
		private string _NombreMaestro;
		
		private string _Dirección;
		
		private EntitySet<tblCargasAlumno> _tblCargasAlumnos;
		
		private EntitySet<tblCargasDocente> _tblCargasDocentes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaestroIDChanging(int value);
    partial void OnMaestroIDChanged();
    partial void OnNombreMaestroChanging(string value);
    partial void OnNombreMaestroChanged();
    partial void OnDirecciónChanging(string value);
    partial void OnDirecciónChanged();
    #endregion
		
		public tblMaestro()
		{
			this._tblCargasAlumnos = new EntitySet<tblCargasAlumno>(new Action<tblCargasAlumno>(this.attach_tblCargasAlumnos), new Action<tblCargasAlumno>(this.detach_tblCargasAlumnos));
			this._tblCargasDocentes = new EntitySet<tblCargasDocente>(new Action<tblCargasDocente>(this.attach_tblCargasDocentes), new Action<tblCargasDocente>(this.detach_tblCargasDocentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaestroID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaestroID
		{
			get
			{
				return this._MaestroID;
			}
			set
			{
				if ((this._MaestroID != value))
				{
					this.OnMaestroIDChanging(value);
					this.SendPropertyChanging();
					this._MaestroID = value;
					this.SendPropertyChanged("MaestroID");
					this.OnMaestroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMaestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreMaestro
		{
			get
			{
				return this._NombreMaestro;
			}
			set
			{
				if ((this._NombreMaestro != value))
				{
					this.OnNombreMaestroChanging(value);
					this.SendPropertyChanging();
					this._NombreMaestro = value;
					this.SendPropertyChanged("NombreMaestro");
					this.OnNombreMaestroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this.OnDirecciónChanging(value);
					this.SendPropertyChanging();
					this._Dirección = value;
					this.SendPropertyChanged("Dirección");
					this.OnDirecciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMaestro_tblCargasAlumno", Storage="_tblCargasAlumnos", ThisKey="MaestroID", OtherKey="MaestroID")]
		public EntitySet<tblCargasAlumno> tblCargasAlumnos
		{
			get
			{
				return this._tblCargasAlumnos;
			}
			set
			{
				this._tblCargasAlumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMaestro_tblCargasDocente", Storage="_tblCargasDocentes", ThisKey="MaestroID", OtherKey="MaestroID")]
		public EntitySet<tblCargasDocente> tblCargasDocentes
		{
			get
			{
				return this._tblCargasDocentes;
			}
			set
			{
				this._tblCargasDocentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblMaestro = this;
		}
		
		private void detach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblMaestro = null;
		}
		
		private void attach_tblCargasDocentes(tblCargasDocente entity)
		{
			this.SendPropertyChanging();
			entity.tblMaestro = this;
		}
		
		private void detach_tblCargasDocentes(tblCargasDocente entity)
		{
			this.SendPropertyChanging();
			entity.tblMaestro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMaterias")]
	public partial class tblMateria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MateriaID;
		
		private string _NombreMateria;
		
		private EntitySet<tblCargasAlumno> _tblCargasAlumnos;
		
		private EntitySet<tblCargasDocente> _tblCargasDocentes;
		
		private EntitySet<tblMateriasCarrera> _tblMateriasCarreras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMateriaIDChanging(int value);
    partial void OnMateriaIDChanged();
    partial void OnNombreMateriaChanging(string value);
    partial void OnNombreMateriaChanged();
    #endregion
		
		public tblMateria()
		{
			this._tblCargasAlumnos = new EntitySet<tblCargasAlumno>(new Action<tblCargasAlumno>(this.attach_tblCargasAlumnos), new Action<tblCargasAlumno>(this.detach_tblCargasAlumnos));
			this._tblCargasDocentes = new EntitySet<tblCargasDocente>(new Action<tblCargasDocente>(this.attach_tblCargasDocentes), new Action<tblCargasDocente>(this.detach_tblCargasDocentes));
			this._tblMateriasCarreras = new EntitySet<tblMateriasCarrera>(new Action<tblMateriasCarrera>(this.attach_tblMateriasCarreras), new Action<tblMateriasCarrera>(this.detach_tblMateriasCarreras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MateriaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MateriaID
		{
			get
			{
				return this._MateriaID;
			}
			set
			{
				if ((this._MateriaID != value))
				{
					this.OnMateriaIDChanging(value);
					this.SendPropertyChanging();
					this._MateriaID = value;
					this.SendPropertyChanged("MateriaID");
					this.OnMateriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMateria", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string NombreMateria
		{
			get
			{
				return this._NombreMateria;
			}
			set
			{
				if ((this._NombreMateria != value))
				{
					this.OnNombreMateriaChanging(value);
					this.SendPropertyChanging();
					this._NombreMateria = value;
					this.SendPropertyChanged("NombreMateria");
					this.OnNombreMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMateria_tblCargasAlumno", Storage="_tblCargasAlumnos", ThisKey="MateriaID", OtherKey="MateriaID")]
		public EntitySet<tblCargasAlumno> tblCargasAlumnos
		{
			get
			{
				return this._tblCargasAlumnos;
			}
			set
			{
				this._tblCargasAlumnos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMateria_tblCargasDocente", Storage="_tblCargasDocentes", ThisKey="MateriaID", OtherKey="MateriaID")]
		public EntitySet<tblCargasDocente> tblCargasDocentes
		{
			get
			{
				return this._tblCargasDocentes;
			}
			set
			{
				this._tblCargasDocentes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMateria_tblMateriasCarrera", Storage="_tblMateriasCarreras", ThisKey="MateriaID", OtherKey="MateriaID")]
		public EntitySet<tblMateriasCarrera> tblMateriasCarreras
		{
			get
			{
				return this._tblMateriasCarreras;
			}
			set
			{
				this._tblMateriasCarreras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblMateria = this;
		}
		
		private void detach_tblCargasAlumnos(tblCargasAlumno entity)
		{
			this.SendPropertyChanging();
			entity.tblMateria = null;
		}
		
		private void attach_tblCargasDocentes(tblCargasDocente entity)
		{
			this.SendPropertyChanging();
			entity.tblMateria = this;
		}
		
		private void detach_tblCargasDocentes(tblCargasDocente entity)
		{
			this.SendPropertyChanging();
			entity.tblMateria = null;
		}
		
		private void attach_tblMateriasCarreras(tblMateriasCarrera entity)
		{
			this.SendPropertyChanging();
			entity.tblMateria = this;
		}
		
		private void detach_tblMateriasCarreras(tblMateriasCarrera entity)
		{
			this.SendPropertyChanging();
			entity.tblMateria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMateriasCarrera")]
	public partial class tblMateriasCarrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CarreraID;
		
		private int _MateriaID;
		
		private EntityRef<tblCarrera> _tblCarrera;
		
		private EntityRef<tblMateria> _tblMateria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarreraIDChanging(int value);
    partial void OnCarreraIDChanged();
    partial void OnMateriaIDChanging(int value);
    partial void OnMateriaIDChanged();
    #endregion
		
		public tblMateriasCarrera()
		{
			this._tblCarrera = default(EntityRef<tblCarrera>);
			this._tblMateria = default(EntityRef<tblMateria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarreraID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CarreraID
		{
			get
			{
				return this._CarreraID;
			}
			set
			{
				if ((this._CarreraID != value))
				{
					if (this._tblCarrera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarreraIDChanging(value);
					this.SendPropertyChanging();
					this._CarreraID = value;
					this.SendPropertyChanged("CarreraID");
					this.OnCarreraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MateriaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MateriaID
		{
			get
			{
				return this._MateriaID;
			}
			set
			{
				if ((this._MateriaID != value))
				{
					if (this._tblMateria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMateriaIDChanging(value);
					this.SendPropertyChanging();
					this._MateriaID = value;
					this.SendPropertyChanged("MateriaID");
					this.OnMateriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCarrera_tblMateriasCarrera", Storage="_tblCarrera", ThisKey="CarreraID", OtherKey="CarreraID", IsForeignKey=true)]
		public tblCarrera tblCarrera
		{
			get
			{
				return this._tblCarrera.Entity;
			}
			set
			{
				tblCarrera previousValue = this._tblCarrera.Entity;
				if (((previousValue != value) 
							|| (this._tblCarrera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCarrera.Entity = null;
						previousValue.tblMateriasCarreras.Remove(this);
					}
					this._tblCarrera.Entity = value;
					if ((value != null))
					{
						value.tblMateriasCarreras.Add(this);
						this._CarreraID = value.CarreraID;
					}
					else
					{
						this._CarreraID = default(int);
					}
					this.SendPropertyChanged("tblCarrera");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMateria_tblMateriasCarrera", Storage="_tblMateria", ThisKey="MateriaID", OtherKey="MateriaID", IsForeignKey=true)]
		public tblMateria tblMateria
		{
			get
			{
				return this._tblMateria.Entity;
			}
			set
			{
				tblMateria previousValue = this._tblMateria.Entity;
				if (((previousValue != value) 
							|| (this._tblMateria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMateria.Entity = null;
						previousValue.tblMateriasCarreras.Remove(this);
					}
					this._tblMateria.Entity = value;
					if ((value != null))
					{
						value.tblMateriasCarreras.Add(this);
						this._MateriaID = value.MateriaID;
					}
					else
					{
						this._MateriaID = default(int);
					}
					this.SendPropertyChanged("tblMateria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ObtenerUsuariosResult
	{
		
		private int _Id;
		
		private string _Usuario;
		
		private string _Contraseña;
		
		public ObtenerUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
	}
	
	public partial class BuscarAlumnoResult
	{
		
		private int _Id;
		
		private string _Alumno;
		
		private string _Carrera;
		
		public BuscarAlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				if ((this._Alumno != value))
				{
					this._Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
	}
	
	public partial class BuscarAlumnoIDPorNombreAlumnoResult
	{
		
		private int _Id;
		
		public BuscarAlumnoIDPorNombreAlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class BuscarCargaAlumnoResult
	{
		
		private int _Id;
		
		private string _Alumno;
		
		private string _Carrera;
		
		private string _Materia;
		
		private string _Maestro;
		
		public BuscarCargaAlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				if ((this._Alumno != value))
				{
					this._Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this._Materia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maestro
		{
			get
			{
				return this._Maestro;
			}
			set
			{
				if ((this._Maestro != value))
				{
					this._Maestro = value;
				}
			}
		}
	}
	
	public partial class BuscarCargaDocenteResult
	{
		
		private int _Id;
		
		private string _Maestro;
		
		private string _Carrera;
		
		private string _Materia;
		
		public BuscarCargaDocenteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maestro
		{
			get
			{
				return this._Maestro;
			}
			set
			{
				if ((this._Maestro != value))
				{
					this._Maestro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this._Materia = value;
				}
			}
		}
	}
	
	public partial class BuscarCarreraResult
	{
		
		private int _Id;
		
		private string _Carrera;
		
		public BuscarCarreraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
	}
	
	public partial class BuscarMaestroResult
	{
		
		private int _Id;
		
		private string _Maestro;
		
		private string _Dirección;
		
		public BuscarMaestroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maestro
		{
			get
			{
				return this._Maestro;
			}
			set
			{
				if ((this._Maestro != value))
				{
					this._Maestro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this._Dirección = value;
				}
			}
		}
	}
	
	public partial class BuscarMaestrosPorMateriaIDResult
	{
		
		private int _Id;
		
		private string _Maestro;
		
		public BuscarMaestrosPorMateriaIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maestro
		{
			get
			{
				return this._Maestro;
			}
			set
			{
				if ((this._Maestro != value))
				{
					this._Maestro = value;
				}
			}
		}
	}
	
	public partial class BuscarMateriasPorCarreraIDResult
	{
		
		private int _Id;
		
		private string _Materia;
		
		public BuscarMateriasPorCarreraIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this._Materia = value;
				}
			}
		}
	}
	
	public partial class BuscarUsuarioResult
	{
		
		private int _Id;
		
		private string _Usuario;
		
		private string _Contraseña;
		
		public BuscarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
	}
	
	public partial class ObtenerAlumnosResult
	{
		
		private int _Id;
		
		private string _Alumno;
		
		private string _Carrera;
		
		public ObtenerAlumnosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				if ((this._Alumno != value))
				{
					this._Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
	}
	
	public partial class ObtenerCargasAlumnosResult
	{
		
		private int _Id;
		
		private string _Alumno;
		
		private string _Carrera;
		
		private string _Materia;
		
		private string _Maestro;
		
		public ObtenerCargasAlumnosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				if ((this._Alumno != value))
				{
					this._Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this._Materia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maestro
		{
			get
			{
				return this._Maestro;
			}
			set
			{
				if ((this._Maestro != value))
				{
					this._Maestro = value;
				}
			}
		}
	}
	
	public partial class ObtenerCargasDocentesResult
	{
		
		private int _Id;
		
		private string _Maestro;
		
		private string _Carrera;
		
		private string _Materia;
		
		public ObtenerCargasDocentesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maestro
		{
			get
			{
				return this._Maestro;
			}
			set
			{
				if ((this._Maestro != value))
				{
					this._Maestro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this._Materia = value;
				}
			}
		}
	}
	
	public partial class ObtenerCarrerasResult
	{
		
		private int _Id;
		
		private string _Carrera;
		
		public ObtenerCarrerasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this._Carrera = value;
				}
			}
		}
	}
	
	public partial class ObtenerMaestrosResult
	{
		
		private int _Id;
		
		private string _Maestro;
		
		private string _Dirección;
		
		public ObtenerMaestrosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maestro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Maestro
		{
			get
			{
				return this._Maestro;
			}
			set
			{
				if ((this._Maestro != value))
				{
					this._Maestro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this._Dirección = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
